// Code generated by goctl. DO NOT EDIT.
// Source: userrpc.proto

package server

import (
	"context"

	"go-0-sd/user/userrpc/internal/logic"
	"go-0-sd/user/userrpc/internal/svc"
	"go-0-sd/user/userrpc/userrpc"
)

type UserrpcServer struct {
	svcCtx *svc.ServiceContext
	userrpc.UnimplementedUserrpcServer
}

func NewUserrpcServer(svcCtx *svc.ServiceContext) *UserrpcServer {
	return &UserrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserrpcServer) GetUserInfo(ctx context.Context, in *userrpc.Request) (*userrpc.Response, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
